### ISSUE TITLE
looses wifi connection in +- one day

### ISSUE THREAD

**Issue by jlandegent** [AWSW-de/WordClock-16x8-LED-matrix#15]
it is not possible to login after one day. the board looses connection with the wifi. ip's are not seen in the router anymore or ip scan. tested with two different setups, two different wifi spots. maybe a scheduled restart can be implemented to keep alive the wifi?

**Comment by AWSW-de** [comment]
Hello, 
are you using the recommended board for the project or a clone? I am running several WordClock with both ESP32 models and the run for months and are triggered each day from my smart home environment successfully…. The used router and chip are a variable of course. How far is the device away from your router? Maybe to weak signal?
A maintenance restart could be added, but there are several thousand devices now running and this is the first report to this. 
So please try to sort the above named reasons out before we add functionality that might not help with the problem in the end.
Thanks and kind regards =)

**Comment by jlandegent** [comment]
use for several days without reset my router, the clocks remain connected. so it means that when wifi signal is lost, there will be no handshake anymoreand the clocks will functioning offline.

**Comment by AWSW-de** [comment]
V3.7.0 addresses this issue. The ESP32 seems to try only a few minutes on its own to reconnect. After this it stops the reconnect tries. In the new version WordClock activly checks its connection every minute and will perform theses actions:

- WordClock will check its connection to your WiFi every 60 seconds (1 minute(s)). 
- If the WiFi cannot be reached anymore it will continue to work offline for 600 seconds (10 minutes), but will flash the WiFi LEDs in blue, yellow and red then. 
- If after 1800 seconds (30 minutes) the WiFi can still not be reconnected, WordClock will reboot automatically to solve the connection problem. 
- In case the WiFi then still not is able to reach for 100 tries, the configuration will be set to default. It is expected then, that the WiFi will not be available anymore, e.g. due to a change of your router, etc...

The option can be turned off in case someone will not like this new function, but will be enabled by default:

![Unbenannt](https://github.com/AWSW-de/WordClock-16x8-LED-matrix/assets/34800740/1c0e91fb-2fcb-4d25-a7b6-24faccf4bbef)

Hope to help! 

Kind regards AWSW
